# Generated by Django 4.1.7 on 2023-04-12 11:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_title_az_category_title_en_news_content_az_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='use in english', null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_az',
            field=ckeditor.fields.RichTextField(blank=True, help_text='use in english', null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='use in english', null=True),
        ),
    ]
