# Generated by Django 4.1.7 on 2023-04-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='description_az',
            field=models.TextField(help_text='About this service', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='description_en',
            field=models.TextField(help_text='About this service', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='title_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
