# Generated by Django 4.1.7 on 2023-04-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_settings_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(help_text='About this service', max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='description_az',
            field=models.TextField(help_text='About this service', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='description_en',
            field=models.TextField(help_text='About this service', max_length=1000, null=True),
        ),
    ]
