# Generated by Django 4.1.7 on 2023-04-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_services_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='work_time1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='work_time2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
