# Generated by Django 4.1.7 on 2023-05-21 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_doctors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctors',
            options={'verbose_name_plural': 'Doctors'},
        ),
    ]
