# Generated by Django 4.1.7 on 2023-05-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_doctors_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='image',
            field=models.ImageField(null=True, upload_to='doctors'),
        ),
    ]
