# Generated by Django 4.1.7 on 2023-05-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_doctors_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='description_en',
            field=models.TextField(null=True),
        ),
    ]
