# Generated by Django 4.1.7 on 2023-05-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_doctors_description_az_doctors_description_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='education_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='education_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='position_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='position_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
