# Generated by Django 4.1.7 on 2023-05-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='problem',
            field=models.TextField(),
        ),
    ]
