# Generated by Django 4.1.7 on 2023-05-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images'),
        ),
    ]
