# Generated by Django 4.1.7 on 2023-06-15 13:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_services_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='About this service', max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='description_az',
            field=ckeditor.fields.RichTextField(help_text='About this service', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='description_en',
            field=ckeditor.fields.RichTextField(help_text='About this service', max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
